# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b468924a4373ee5d6ecc85203a699b7d9a55107feb1b142630f2cc366e1a806fc9c0b7be09d7768cf382b9289e589586541edcd669e59897d17ddcbf9eff92df

test:
  secret_key_base: 21096ad1467f48773a582fceb110f2d3acf1745637c3fe7ace325c061cdc7befd3295aea77263414b5eff2dc9c3d675cb8b2ab18ff387b2551123d42100844ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
